require("user.options")
require("user.utils")
require("user.lsp")
require("user.keys")
require("user.plugins")
require("user.toggleterm")
require("nvim-tree").setup()
require("nvim-autopairs").setup{}
require("neoscroll").setup()
require("bufferline").setup{}
require("feline").setup()
